id: P8E1EEE84
initial_creation_type: input
source_metadata:
  title: Nyoshul Lungtok Series
  language: bo
  description: 'Texts by the great Dzogchen master Nyoshul Lungtok Tenpe Nyima (smyo
    shul lung rtogs bstan pa''i nyi ma, 1829–1901/2):'
  volume:
    42f55acf47754527986a52739490e8ad:
      title: Bodhicitta Aspiration
      parent: Prayers and Practices
    0a7c190fb0cf4ad9ad161f260584507b:
      title: Prayer to Avalokiteśvara
      parent: Prayers and Practices
created_at: '2022-03-01T01:06:42.462153'
last_modified_at: '2022-03-01T01:06:42.462156'
statistics:
  total_words: 503
  total_non_words: 38
quality:
  non_words_ratio: 0.08
